// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Volumes/perez-backup/business-projects/fitforge-mobile/node_modules/react');
var { Component } = React;
var ReactNative = require('/Volumes/perez-backup/business-projects/fitforge-mobile/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('fitforge-mobile', appParameters);
});
require('/Volumes/perez-backup/business-projects/fitforge-mobile/index.android.js');